parameters:
    jwt_key:
        kid: '5eda9b41-085c-403f-85e7-50d3b4131082'
        public: 'file://%kernel.project_dir%/var/public.key'
        private: 'file://%kernel.project_dir%/tests/resources/private.key'
    encryption_key: '%kernel.project_dir%/tests/resources/encryption.key'
    access_token_ttl: PT1H
    refresh_token_ttl: P1M
    auth_code_ttl: PT1M
    enable_client_credentials_grant: true
    enable_password_grant: true
    enable_refresh_token_grant: true
    enable_auth_code_grant: true
    enable_implicit_grant: true

services:
    _defaults:
        public: true

    App\Tests\TestHelper:
        arguments:
            - '@App\Service\Api\ClientConnectorInterface'

    App\Repository\ScopeRepository:
        public: true

    App\Service\Api\UserConnectorInterface:
        class: App\Tests\Mock\UserConnectorMock

    App\Service\Api\ClientConnectorInterface:
        class: App\Tests\Mock\ClientConnectorMock
