# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    user_auth_endpoint: 'http://host.docker.internal:9001/api/v1/auth'
    user_fetch_endpoint: 'http://host.docker.internal:9001/api/v1/user/{id}'
    client_auth_endpoint: 'http://host.docker.internal:9002/api/v1/auth'
    client_query_endpoint: 'http://host.docker.internal:9002/api/v1/query'
    two_fa_auth_endpoint: 'http://host.docker.internal:9003/api/v1/auth'
    two_fa_index_endpoint: 'http://localhost:9003/2fa/verify/{id}'
    two_fa_verification_enabled: '%env(bool:TWO_FA_VERIFICATION_ENABLED)%'
    two_fa_verification_conditional: '%env(bool:TWO_FA_VERIFICATION_CONDITIONAL)%'
    jwt_key:
        kid: '5eda9b41-085c-403f-85e7-50d3b4131082'
        public: 'file://%kernel.project_dir%/var/public.key'
        private: 'file://%kernel.project_dir%/var/private.key'
    encryption_key: '%kernel.project_dir%/var/encryption.key'
    access_token_ttl: PT1H
    refresh_token_ttl: P1M
    auth_code_ttl: PT1M
    enable_client_credentials_grant: true
    enable_password_grant: true
    enable_refresh_token_grant: true
    enable_auth_code_grant: true
    enable_implicit_grant: false

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: '%kernel.project_dir%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Security\AuthAuthenticator:
        class: App\Security\AuthAuthenticator
        calls:
            - setTwoFaConfigurationParams: [ '%two_fa_verification_enabled%', '%two_fa_verification_conditional%', '%two_fa_index_endpoint%' ]

    App\Service\Api\UserConnectorInterface:
        class: App\Service\Api\UserConnector
        calls:
            - setUserAuthEndpoint: [ '%user_auth_endpoint%' ]
            - setUserFetchEndpoint: [ '%user_fetch_endpoint%' ]

    App\Service\Api\ClientConnectorInterface:
        class: App\Service\Api\ClientConnector
        calls:
            - setClientAuthEndpoint: [ '%client_auth_endpoint%' ]
            - setQueryEndpoint: [ '%client_query_endpoint%' ]

    App\Service\Api\TwoFaConnector:
        class: App\Service\Api\TwoFaConnector
        calls:
            - setAuthEndpoint: [ '%two_fa_auth_endpoint%' ]

    App\Service\JwtTokenGenerator:
        arguments:
            - '%jwt_key%'

    App\OAuth\AuthorizationServerFactory:
        calls:
            - setJwtKey: ['%jwt_key%']
            - setEncryptionKey: ['%encryption_key%']
            - setAccessTokenTtl: ['%access_token_ttl%']
            - setRefreshTokenTtl: ['%refresh_token_ttl%']
            - setAuthCodeTtl: ['%auth_code_ttl%']
            - enableClientCredentialsGrant: ['%enable_client_credentials_grant%']
            - enablePasswordGrant: ['%enable_password_grant%']
            - enableRefreshTokenGrant: ['%enable_refresh_token_grant%']
            - enableAuthCodeGrant: ['%enable_auth_code_grant%']
            - enableImplicitGrant: ['%enable_implicit_grant%']

    League\OAuth2\Server\AuthorizationServer:
        factory: ['@App\OAuth\AuthorizationServerFactory', 'create']

    Symfony\Bridge\PsrHttpMessage\HttpFoundationFactoryInterface:
        class: Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory

    Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface:
        class: Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory

    Psr\Http\Message\ResponseFactoryInterface:
        class: Nyholm\Psr7\Factory\Psr17Factory

    League\Event\Emitter:
        class: League\Event\Emitter
        calls:
            - useListenerProvider: ['@App\Service\SymfonyLeagueEventListenerProvider']
