# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    fallback_app_secret: '%env(APP_SECRET)%'
    fallback_db_user: '%env(DB_USER)%'
    fallback_db_password: '%env(DB_PASSWORD)%'
    login_two_fa_enabled: '%env(bool:LOGIN_TWO_FA_ENABLED)%'
    oidc_extra_claims: '%env(string:OIDC_EXTRA_CLAIMS)%'
    reset_password_url: '%env(string:RESET_PASSWORD_URL)%'
    user_query_endpoint: '%env(string:USER_QUERY_ENDPOINT)%'
    user_auth_endpoint: '%env(string:USER_AUTH_ENDPOINT)%'
    user_fetch_endpoint: '%env(string:USER_FETCH_ENDPOINT)%'
    client_auth_endpoint: '%env(string:CLIENT_AUTH_ENDPOINT)%'
    client_query_endpoint: '%env(string:CLIENT_QUERY_ENDPOINT)%'
    two_fa_auth_endpoint: '%env(string:TWO_FA_AUTH_ENDPOINT)%'
    two_fa_index_endpoint: '%env(string:TWO_FA_INDEX_ENDPOINT)%'
    jwt_include_groups_claim: '%env(bool:JWT_INCLUDE_GROUPS_CLAIM)%'
    jwt_groups_claim_limit: '%env(int:JWT_GROUPS_CLAIM_LIMIT)%'
    jwt_key:
        public: 'file://%env(JWT_PUBLIC_KEY_PATH)%'
        private: 'file://%env(JWT_PRIVATE_KEY_PATH)%'
    encryption_key: '%env(ENCRYPTION_KEY_PATH)%'
    access_token_ttl: '%env(string:OAUTH2_ACCESS_TOKEN_TTL)%'
    refresh_token_ttl: '%env(string:OAUTH2_REFRESH_TOKEN_TTL)%'
    auth_code_ttl: '%env(string:OAUTH2_AUTH_CODE_TTL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: '%kernel.project_dir%'

    # Makes sgoranov\IdentityLinkShared services available
    sgoranov\IdentityLinkShared\:
        resource: '../vendor/sgoranov/identity-link-shared/src/*'

    sgoranov\IdentityLinkShared\Security\AccessTokenHandler:
        calls:
            - method: setJwtPublicKey
              arguments:
                  - '@=service("App\\Security\\Jwt\\JwtConfig").getPublicKey()'

    sgoranov\IdentityLinkShared\EventListener\XForwardedPrefixListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 10 }

    sgoranov\IdentityLinkShared\EventListener\LocaleListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 15 }

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Security\Jwt\JwtConfig:
        arguments:
            $config: '%jwt_key%'

    App\Security\EncryptionKeyLoader:
      class: App\Security\EncryptionKeyLoader
      calls:
        - setEncryptionKeyPath: [ '%encryption_key%' ]

    App\Security\AuthorizationEndpointAuthenticator:
        class: App\Security\AuthorizationEndpointAuthenticator

    App\Security\LoginFlowConfig:
        arguments:
            $twoFactorEnabled: '%login_two_fa_enabled%'

    App\LeagueOAuth2\Repository\AccessTokenRepository:
        class: App\LeagueOAuth2\Repository\AccessTokenRepository
        calls:
            - configureJwtGroupsClaims: [ '%jwt_include_groups_claim%', '%jwt_groups_claim_limit%' ]

    App\Api\Contract\UserConnectorInterface:
        class: App\Api\IdentityLink\Connector\DbUserConnector
        calls:
            - setUserAuthEndpoint: [ '%user_auth_endpoint%' ]
            - setUserFetchEndpoint: [ '%user_fetch_endpoint%' ]
            - setQueryEndpoint: [ '%user_query_endpoint%' ]

    App\Api\Contract\ClientConnectorInterface:
        class: App\Api\IdentityLink\Connector\DbClientConnector
        calls:
            - setClientAuthEndpoint: [ '%client_auth_endpoint%' ]
            - setQueryEndpoint: [ '%client_query_endpoint%' ]

    App\Api\Contract\TwoFaConnectorInterface:
        class: App\Api\IdentityLink\Connector\TwoFaConnector
        calls:
            - setAuthEndpoint: [ '%two_fa_auth_endpoint%' ]

    App\Service\OidcExtraClaimsProvider:
        arguments:
            $parameterBag: '@parameter_bag'

    OpenIDConnectServer\ClaimExtractor:
        class: OpenIDConnectServer\ClaimExtractor
        arguments:
            - '@App\Service\OidcExtraClaimsProvider'

    OpenIDConnectServer\IdTokenResponse:
        class: OpenIDConnectServer\IdTokenResponse
        arguments:
            - '@App\LeagueOAuth2\Repository\UserRepository'
            - '@OpenIDConnectServer\ClaimExtractor'

    App\LeagueOAuth2\AuthorizationServerFactory:
        calls:
            - setAccessTokenTtl: ['%access_token_ttl%']
            - setRefreshTokenTtl: ['%refresh_token_ttl%']
            - setAuthCodeTtl: ['%auth_code_ttl%']
            - setEnabledGrantsFromString: ['%env(string:OAUTH2_ENABLED_GRANTS)%']

    League\OAuth2\Server\AuthorizationServer:
        factory: ['@App\LeagueOAuth2\AuthorizationServerFactory', 'create']

    Symfony\Bridge\PsrHttpMessage\HttpFoundationFactoryInterface:
        class: Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory

    Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface:
        class: Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory

    Psr\Http\Message\ResponseFactoryInterface:
        class: Nyholm\Psr7\Factory\Psr17Factory
